# W9 - Wide

This notebook contains personal notes and Python, Numpy and Latex of exercises from the "AI by Hand ✍️ Workbook" by Prof. Tom Yeh.


Reference: [AI by Hand ✍️  Workbook](https://www.byhand.ai/t/workbook)

*Contents*

- Wide Neurons
- Wide Hidden Layers

In [1]:
from ai_by_hand_utils.neural_network import Layer, NeuralNetwork
from ai_by_hand_utils.activation import ReLU

import numpy as np

In [ ]:
# Exercise 1 - One weight neuron 
input = np.matrix([[2]])
layers = [
    Layer(
        weights=np.matrix([[1]]),
        bias=np.array([0]),
        activation_f=ReLU
    )
    ]

nn = NeuralNetwork(layers=layers)

nn.forward_propagation(input=input)

Input:
[[2]]
Muiltiplying with weights:
[[1]]
Weights size: (1, 1)  ,  input size: 1
[[2]]


matrix([[2]])

In [9]:
# Exercise 6 - 4 features input, 3 neurons with 4 weights, 3 outputs
input = np.matrix([[2,1,3,1]])
layers = [
    Layer(
        weights=np.matrix([[1,1,0,1],
                           [1,-1,0,0],
                           [-1,0,1,0]]),
        bias=np.matrix([[0,1,3]]),
        activation_f=ReLU
    )
    ]

nn = NeuralNetwork(layers=layers)

nn.forward_propagation(input=input)

Input:
[[2 1 3 1]]
Muiltiplying with weights:
[[ 1  1  0  1]
 [ 1 -1  0  0]
 [-1  0  1  0]]
Weights size: (3, 4)  ,  input size: 4
[[4 2 4]]


matrix([[4, 2, 4]])

In [13]:
# Exercise 25 - Input= 5 features, 4 layers

input = np.matrix([[2,1,3,0,-1]])

layers = [
    Layer(
        weights=np.matrix([[1,0,0,0,-1],
                           [0,1,1,0,0],
                           [0,0,1,1,1],
                           [0,0,0,0,2]]),
        bias=np.matrix([[0,0,0,1]]),
        activation_f=ReLU
    ),

        Layer(
        weights=np.matrix([[1,0,0,-1],
                           [0,1,-1,0],
                           [1,0,0,0]]),
        bias=np.matrix([[0,0,-2]]),
        activation_f=ReLU
    ),

        Layer(
        weights=np.matrix([[1,0,-1],
                           [1,1,0]]),
        bias=np.matrix([[0,1]]),
        activation_f=ReLU
    ),
    Layer(
        weights=np.matrix([[-1,1]]),
        bias=np.matrix([[1]]),
        activation_f=ReLU)
    ]

nn = NeuralNetwork(layers=layers)

nn.forward_propagation(input=input)

Input:
[[ 2  1  3  0 -1]]
Muiltiplying with weights:
[[ 1  0  0  0 -1]
 [ 0  1  1  0  0]
 [ 0  0  1  1  1]
 [ 0  0  0  0  2]]
Weights size: (4, 5)  ,  input size: 5
[[3 4 2 0]]
Muiltiplying with weights:
[[ 1  0  0 -1]
 [ 0  1 -1  0]
 [ 1  0  0  0]]
Weights size: (3, 4)  ,  input size: 4
[[3 2 1]]
Muiltiplying with weights:
[[ 1  0 -1]
 [ 1  1  0]]
Weights size: (2, 3)  ,  input size: 3
[[2 6]]
Muiltiplying with weights:
[[-1  1]]
Weights size: (1, 2)  ,  input size: 2
[[5]]


matrix([[5]])