# W7 - Connection

This notebook contains personal notes and Python, Numpy and Latex of exercises from the "AI by Hand ✍️ Workbook" by Prof. Tom Yeh.


Reference: [AI by Hand ✍️  Workbook](https://www.byhand.ai/t/workbook)

*Contents*

- Connection is about using the weight matrix $W$ with booleans to connect input features $x_1, x_2, ...$ nodes to neuron weigth nodes $w_{1,1}, w_{1,2}, ...$
- Topologies:
    - One to Many 
    - Many to one
    - Fully connected (also known as dense)


In [2]:
import numpy as np

In [ ]:
# Exercise 17 One input feature to Many 
print("Inputs")
X = np.array([42,66])
print(X)
W = np.matrix([
    [0,1],
    [0,1],
    [0,1]]
    )
print("Weights:")
print(W)
print("Result:")
print(np.dot(W,X.T))

Inputs
[42 66]
Weights:
[[0 1]
 [0 1]
 [0 1]]
Result:
[[66 66 66]]


In [16]:
# Exercise 24 One to many
print("Inputs")
X = np.array([42,66,23])
print(X)
W = np.matrix([
    [0,1,0],
    [0,1,0],
    [0,1,0],
    [0,1,0],
    [0,1,0]]
    )
print("Weights:")
print(W)
print("Result:")
print(np.dot(W,X.T))

Inputs
[42 66 23]
Weights:
[[0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]
Result:
[[66 66 66 66 66]]
