# W8 - Hidden Layer

This notebook contains personal notes and Python, Numpy and Latex of exercises from the "AI by Hand ✍️ Workbook" by Prof. Tom Yeh.


Reference: [AI by Hand ✍️  Workbook](https://www.byhand.ai/t/workbook)

*Contents*

So far we covered one neuron layer. Now we are concatennating neuron layers. The output of one neuron is used as an output of the next one. 

Hidden neuron layers stil have a bias and activation component per layer. 

The architecture of this layers if flexible:

- You can end th one vector $y$ per input vector $x$, useful for classification 
- Or just one $y$ per multiple $x$, useful for sensors and state predictions


### Questions

[Q] What is the official nomeclature of input vectors and output vectors?

- $x$ is usually called features
- $y$ is usually called targets or predictions
- The output of a hidden layer is usually called *Activation Vector* $a$ or *Hidden State* $h$ 


In [11]:
import numpy as np

def ReLU(x):
    return np.maximum(0,x)

In [12]:
# Exercise 1 
x = np.matrix([[3,1]]) 
w = np.matrix([[1,1]])
b = np.array([0])

# hidden layer
h = np.matrix([[1]]) # dim 1x1
h_b = np.array([-1])

a = ReLU(np.dot(w,x.T) + b)

print("Hidden layer result:")
print(a)
y = ReLU(np.dot(h, a.T) + h_b)

print("y:")
print(y)

Hidden layer result:
[[4]]
y:
[[3]]


In [23]:
# Exercise 17 
x = np.matrix([[2,1,3]]) 
w = np.matrix([
    [0,1,1],
    [1,1,0],
    [1,0,1],
    [1,0,0]
    ]
    )

b = np.matrix([[0,0,0,-1]])

# hidden layer
h = np.matrix([
    [1,1,0,0],
    [0,0,1,1]])

h_b = np.matrix([[0,-1]])

a = ReLU(np.dot(w,x.T) + b.T) # bias is transposed here

print("Hidden layer result:")
print(a)

y = ReLU(np.dot(h, a) + h_b.T)

print("y:")
print(y)

Hidden layer result:
[[4]
 [3]
 [5]
 [1]]
y:
[[7]
 [5]]


In [24]:
# Exercise 17 
x = np.matrix([[3,2]]) 
w = np.matrix([
    [0,1],
    [1,0],
    [-1,1],
    [0,0],
    [0,-1],
    [1,-1]
    ]
    )

b = np.matrix([[0,0,0,2,0,0]])

# hidden layer
h = np.matrix([[1,1,1,1,1,1]])

h_b = np.matrix([[0]])

a = ReLU(np.dot(w,x.T) + b.T) # bias is transposed here

print("Hidden layer result:")
print(a)

y = ReLU(np.dot(h, a) + h_b.T)

print("y:")
print(y)

Hidden layer result:
[[2]
 [3]
 [0]
 [2]
 [0]
 [1]]
y:
[[8]]


## Neural Network Class 

In [ ]:
# Layer: weights + biases + Activation Function
# Concatenation or structure , list of layers
# Input: np.matrix 

from dataclasses import dataclass
from typing import Callable
import numpy as np


@dataclass
class Layer:
    weights: np.matrix
    bias: np.matrix
    activation_f : Callable

class NeuralNetwork():

    def __init__(self, layers: list[Layer]):
        self.layers = layers

    def multiply(self, input):
        '''
        Processes the multiplications of Input and Layers in the neural network
        input : X

        '''
        print("Input:")
        print(input)
        results = input
        for layer in self.layers:
            print("Muiltiplying with weights:")
            print(layer.weights)
            print(f"Weights size: {layer.weights.shape}  ,  input size: {results.T.size}")

            results = layer.activation_f(np.dot(layer.weights, results.T) + layer.bias.T) 
            
            # Transponsing it to work with the patter so far
            results = results.T

            print(results)
        return results


In [45]:
# Exercise 17 using the NeuralNetwork

layer1 = Layer(
    weights= np.matrix([
        [0,1],
        [1,0],
        [-1,1],
        [0,0],
        [0,-1],
        [1,-1]]),
    bias = np.matrix([[0,0,0,2,0,0]]),
    activation_f= ReLU
)

layer2 = Layer(
    weights= np.matrix([[1,1,1,1,1,1]]),
    bias= np.matrix([[0]]),
    activation_f=ReLU
    )
    

nn = NeuralNetwork(layers=[layer1, layer2])
nn.multiply(input=np.matrix([[3,2]]))

Input:
[[3 2]]
Muiltiplying with weights:
[[ 0  1]
 [ 1  0]
 [-1  1]
 [ 0  0]
 [ 0 -1]
 [ 1 -1]]
Weights size: (6, 2)  ,  input size: 2
[[2 3 0 2 0 1]]
Muiltiplying with weights:
[[1 1 1 1 1 1]]
Weights size: (1, 6)  ,  input size: 6
[[8]]


matrix([[8]])