# W9 - Deep

This notebook contains personal notes and Python, Numpy and Latex of exercises from the "AI by Hand ✍️ Workbook" by Prof. Tom Yeh.


Reference: [AI by Hand ✍️  Workbook](https://www.byhand.ai/t/workbook)

*Contents*

Deep networks contain several concatenated layers of neurons

In [1]:
from ai_by_hand_utils.neural_network import Layer, NeuralNetwork
from ai_by_hand_utils.activation import ReLU

import numpy as np

In [ ]:
# Exercise 3

layers = [
    Layer(weights=np.matrix([1]), bias= np.matrix([0]), activation_f=ReLU),
    Layer(weights=np.matrix([2]), bias= np.matrix([0]), activation_f=ReLU),
    Layer(weights=np.matrix([0]), bias= np.matrix([1]), activation_f=ReLU),
    Layer(weights=np.matrix([0]), bias= np.matrix([2]), activation_f=ReLU),
    Layer(weights=np.matrix([-1]), bias= np.matrix([0]), activation_f=ReLU),
    Layer(weights=np.matrix([2]), bias= np.matrix([5]), activation_f=ReLU),

]

input = np.matrix([2])


nn = NeuralNetwork(layers=layers)
nn.forward_propagation(input=input)

Input:
[[2]]
Muiltiplying with weights:
[[1]]
Weights size: (1, 1)  ,  input size: 1
[[2]]
Muiltiplying with weights:
[[2]]
Weights size: (1, 1)  ,  input size: 1
[[4]]
Muiltiplying with weights:
[[0]]
Weights size: (1, 1)  ,  input size: 1
[[1]]
Muiltiplying with weights:
[[0]]
Weights size: (1, 1)  ,  input size: 1
[[2]]
Muiltiplying with weights:
[[-1]]
Weights size: (1, 1)  ,  input size: 1
[[0]]
Muiltiplying with weights:
[[2]]
Weights size: (1, 1)  ,  input size: 1
[[5]]


matrix([[5]])

In [8]:
# Exercise 25

layers = [
    Layer(weights=np.matrix([[0,1,1],
                            [0,0,1],
                            [1,1,0]]), 
          bias= np.matrix([0,3,0]),
          activation_f=ReLU),
    Layer(weights=np.matrix([[1,0,1],
                            [0,1,0],
                            [-1,0,1]]), 
          bias= np.matrix([0,-1,0]),
          activation_f=ReLU), 
    Layer(weights=np.matrix([[0,0,1],
                            [0,1,0],
                            [1,0,0]]), 
          bias= np.matrix([0,0,0]),
          activation_f=ReLU),
    Layer(weights=np.matrix([[1,1,0],
                            [0,1,1],
                            [1,0,1]]), 
          bias= np.matrix([0,0,0]),
          activation_f=ReLU),
]

input = np.matrix([[2,0,1]])


nn = NeuralNetwork(layers=layers)
nn.forward_propagation(input=input)

Input:
[[2 0 1]]
Muiltiplying with weights:
[[0 1 1]
 [0 0 1]
 [1 1 0]]
Weights size: (3, 3)  ,  input size: 3
[[1 4 2]]
Muiltiplying with weights:
[[ 1  0  1]
 [ 0  1  0]
 [-1  0  1]]
Weights size: (3, 3)  ,  input size: 3
[[3 3 1]]
Muiltiplying with weights:
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Weights size: (3, 3)  ,  input size: 3
[[1 3 3]]
Muiltiplying with weights:
[[1 1 0]
 [0 1 1]
 [1 0 1]]
Weights size: (3, 3)  ,  input size: 3
[[4 6 4]]


matrix([[4, 6, 4]])